var convert = require('../lib'),
  assert = require('assert'),
  tests = {};
tests['measures'] = function () {
  var actual = convert().measures(),
    expected = [
      'Length',
      'Area',
      'Mass',
      'Volume',
      'Each',
      'Temperature',
      'Time',
      'Digital',
      'PartsPer',
      'Speed',
      'Pace',
      'Pressure',
      'Current',
      'Voltage',
      'Power',
      'Reactive power',
      'Apparent power',
      'Energy',
      'Reactive energy',
      'VolumeFlowRate',
      'Illuminance',
      'Frequency',
      'Angle',
      'Charge',
      'Force',
      'Acceleration',
      'Vibration',
      'Density',
      'Humidity',
      'Relative humidity',
      'Torque',
      'Gauge pressure',
      'Currency',
      'Percentage',
      'Pulse frequency',
      'Data',
      'Rotational speed',
      'Scalar',
      'pH',
      'Concentration'
    ];
  assert.deepEqual(actual, expected);
};

module.exports = tests;
